name: "Build and Push Docker Image"
description: "Logs in to Docker Hub, builds and pushes the Docker image"
inputs:
  repo-name:
    description: "The name of the repository"
    required: true
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password"
    required: true
  image-tag:
    description: "The image tag to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build Docker Image
      shell: bash
      run: |
        docker build -t weeturtle/${{ inputs.repo-name }}:${{ inputs.image-tag }} .
        docker tag weeturtle/${{ inputs.repo-name }}:${{ inputs.image-tag }} weeturtle/${{ inputs.repo-name }}:latest

    - name: Push Docker Image
      shell: bash
      run: |
        docker push weeturtle/${{ inputs.repo-name }}:${{ inputs.image-tag }}
        docker push weeturtle/${{ inputs.repo-name }}:latest
