name: Production Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Unit Tests
        env:
          PORT: 3000
        run: yarn test-unit

  build:
    needs: unit_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSKEY }}

      - name: Build Docker Image
        env:
          PORT: 3000
        run: docker build -t weeturtle/${{ github.event.repository.name }}:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push weeturtle/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Deploy Docker Image
        run: echo "Would deploy to cloud service"
